# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-24 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_wine_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
